Repository mozilla-lockwise/lockwise-ios, pull requests merged in 2018-04, with the labels that each got.

#184 UI and spacing improvements to list view
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Storyboard/Base.lproj/ItemList.storyboard
  lockbox-ios/View/ItemListView.swift
Labels: in progress

#191 note the troubleshooting steps if carthage fails on Swift version mis…
  docs/updating_libraries.md
Labels: in progress

#192 Capitalize 'L' in Lockbox
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Storyboard/Base.lproj/EmptyList.xib
  lockbox-ios/Storyboard/de.lproj/EmptyList.strings
  lockbox-ios/Storyboard/en.lproj/EmptyList.strings
  lockbox-ios/Storyboard/es.lproj/EmptyList.strings
Labels: in progress

#200 Refactor view checking to use types
  lockbox-ios/Presenter/RootPresenter.swift
  lockbox-ios/View/RootView.swift
  lockbox-iosTests/RootPresenterSpec.swift
  lockbox-iosTests/RootViewSpec.swift
Labels: in progress

#215 Codecov Tweaks
  Lockbox.xcodeproj/project.pbxproj
  lockbox-ios/Common/Extensions/UIViewController+.swift
  lockbox-ios/Presenter/AutoLockSettingsPresenter.swift
  lockbox-ios/Presenter/FxAPresenter.swift
  lockbox-ios/View/AccountSettingView.swift
  lockbox-ios/View/AutoLockSettingsView.swift
  lockbox-ios/View/ItemDetailView.swift
  lockbox-ios/View/ItemListView.swift
  lockbox-ios/View/RootView.swift
  lockbox-iosTests/MainNavigationControllerSpec.swift
  lockbox-iosTests/RootViewSpec.swift
  lockbox-iosTests/SettingNavigationControllerSpec.swift
  lockbox-iosTests/UserInfoStoreSpec.swift
Labels: in progress

#221 Restore xcode code coverage reports for codecov
  buddybuild_postbuild.sh
Labels: in progress

#220 Point CODEOWNERS to a team, not an individual
  docs/CODEOWNERS
Labels: in progress

#218 Settings Web Views
  Lockbox.xcodeproj/project.pbxproj
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Presenter/RootPresenter.swift
  lockbox-ios/View/RootView.swift
  lockbox-ios/View/SettingWebView.swift
  lockbox-iosTests/RootViewSpec.swift
  lockbox-iosTests/SettingWebViewSpec.swift
Labels: in progress

#217 Add detail label for autolock setting
  lockbox-ios/Presenter/SettingsPresenter.swift
  lockbox-ios/Store/UserInfoStore.swift
  lockbox-ios/View/SettingsView.swift
  lockbox-iosTests/SettingsPresenterSpec.swift
  lockbox-iosTests/SettingsViewSpec.swift
Labels: in progress

#224 Remove iPad device family targeting
  Lockbox.xcodeproj/project.pbxproj
Labels: in progress

#226 Fix warnings & update Carthage for Swift 4.1
  Cartfile.resolved
  lockbox-ios/Common/Helpers/KeyManager.swift
  lockbox-ios/Presenter/ItemListPresenter.swift
Labels: in progress

#231 Add more test data
  lockbox-ios/Action/DataStoreAction.swift
Labels: in progress

#222 Add launch screen storyboard and update welcome screen text
  Lockbox.xcodeproj/project.pbxproj
  lockbox-ios/Common/Resources/Assets.xcassets/lockbox-title.imageset/Contents.json
  lockbox-ios/Common/Resources/Assets.xcassets/lockbox-title.imageset/lockbox.png
  lockbox-ios/Common/Resources/Assets.xcassets/lockbox-title.imageset/lockbox@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/lockbox-title.imageset/lockbox@3x.png
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Common/Resources/Fonts/FiraSans-Bold.ttf
  lockbox-ios/Common/Resources/Fonts/FiraSans-Italic.ttf
  lockbox-ios/Common/Resources/Info.plist
  lockbox-ios/Presenter/RootPresenter.swift
  lockbox-ios/Resources/Fonts/FiraSans-Bold.ttf
  lockbox-ios/Storyboard/Base.lproj/Welcome.storyboard
  lockbox-ios/Storyboard/LaunchScreen.storyboard
  lockbox-ios/Storyboard/de.lproj/Welcome.strings
  lockbox-ios/Storyboard/en.lproj/Welcome.strings
  lockbox-ios/Storyboard/es.lproj/Welcome.strings
  lockbox-iosTests/RootPresenterSpec.swift
Labels: in progress

#238 Bump cjose to 0.6.1
  scripts/update-dependencies
Labels: in progress

#210 Sign out and lock functionality
  Lockbox.xcodeproj/project.pbxproj
  lockbox-ios/Action/SettingAction.swift
  lockbox-ios/Common/Extensions/LAContext+.swift
  lockbox-ios/Common/Extensions/UserDefaults+.swift
  lockbox-ios/Common/Resources/Assets.xcassets/face.imageset/Contents.json
  lockbox-ios/Common/Resources/Assets.xcassets/face.imageset/touchId.png
  lockbox-ios/Common/Resources/Assets.xcassets/face.imageset/touchId@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/face.imageset/touchId@3x.png
  lockbox-ios/Common/Resources/Assets.xcassets/fingerprint.imageset/Contents.json
  lockbox-ios/Common/Resources/Assets.xcassets/fingerprint.imageset/bitmap.png
  lockbox-ios/Common/Resources/Assets.xcassets/fingerprint.imageset/bitmap@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/fingerprint.imageset/bitmap@3x.png
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Presenter/AutoLockSettingsPresenter.swift
  lockbox-ios/Presenter/FxAPresenter.swift
  lockbox-ios/Presenter/RootPresenter.swift
  lockbox-ios/Presenter/SettingListPresenter.swift
  lockbox-ios/Presenter/WelcomePresenter.swift
  lockbox-ios/Store/FxAStore.swift
  lockbox-ios/Store/RouteStore.swift
  lockbox-ios/Storyboard/Base.lproj/SettingList.storyboard
  lockbox-ios/Storyboard/Base.lproj/Welcome.storyboard
  lockbox-ios/Storyboard/de.lproj/SettingList.strings
  lockbox-ios/Storyboard/en.lproj/SettingList.strings
  lockbox-ios/Storyboard/es.lproj/SettingList.strings
  lockbox-ios/View/FxAView.swift
  lockbox-ios/View/NavigationController/SettingNavigationController.swift
  lockbox-ios/View/SettingListView.swift
  lockbox-ios/View/WelcomeView.swift
  lockbox-iosTests/AutoLockSettingsPresenterSpec.swift
  lockbox-iosTests/FxAPresenterSpec.swift
  lockbox-iosTests/LAContext+Spec.swift
  lockbox-iosTests/RootPresenterSpec.swift
  lockbox-iosTests/RootViewSpec.swift
  lockbox-iosTests/SettingActionSpec.swift
  lockbox-iosTests/SettingListPresenterSpec.swift
  lockbox-iosTests/SettingListViewSpec.swift
  lockbox-iosTests/SettingNavigationControllerSpec.swift
  lockbox-iosTests/UserDefaults+Spec.swift
  lockbox-iosTests/WelcomePresenterSpec.swift
  lockbox-iosTests/WelcomeViewSpec.swift
Labels: in progress

#237 Replace App Icon assets to non-masked
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/iTunesArtwork@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/iTunesArtwork_512pt@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_20pt.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_20pt@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_20pt@3x.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_29pt.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_29pt@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_29pt@3x.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_40pt.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_40pt@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_40pt@3x.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_60pt@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_60pt@3x.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_76pt.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_76pt@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_83.5@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_small-1.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_small.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_small@2x-1.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_small@2x-2.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_small@2x-3.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_small@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_small@3x-1.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_small@3x.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_small_40pt.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_small_40pt@2x-1.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_small_40pt@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/AppIcon.appiconset/icon_small_40pt@3x.png
Labels: in progress

#244 Set default button text to "Sign in.." instead of "Get Started"
  lockbox-ios/Storyboard/Base.lproj/Welcome.storyboard
  lockbox-ios/Storyboard/de.lproj/Welcome.strings
  lockbox-ios/Storyboard/en.lproj/Welcome.strings
  lockbox-ios/Storyboard/es.lproj/Welcome.strings
Labels: MVP, P1, bug, in progress

#248 a couple of fixes for the autolock setting header
  lockbox-ios/View/AutoLockSettingsView.swift
Labels: in progress

#246 Minor doc updates
  docs/architecture.md
  docs/install.md
  mkdocs.yml
Labels: chore, in progress

#255 Don't let empty state scroll
  lockbox-ios/View/ItemListView.swift
  lockbox-iosTests/ItemListViewSpec.swift
Labels: bug, in progress

#216 Preferred browser setting and open links in browser
  Lockbox.xcodeproj/project.pbxproj
  lockbox-ios/Action/ExternalLinkAction.swift
  lockbox-ios/Action/RouteAction.swift
  lockbox-ios/Action/SettingAction.swift
  lockbox-ios/Common/Extensions/UIApplication+.swift
  lockbox-ios/Common/Extensions/UserDefaults+.swift
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Common/Resources/Info.plist
  lockbox-ios/Presenter/ItemDetailPresenter.swift
  lockbox-ios/Presenter/PreferredBrowserSettingPresenter.swift
  lockbox-ios/Presenter/RootPresenter.swift
  lockbox-ios/Presenter/SettingListPresenter.swift
  lockbox-ios/View/PreferredBrowserSettingView.swift
  lockbox-ios/View/RootView.swift
  lockbox-ios/View/SettingListView.swift
  lockbox-iosTests/ExternalLinkActionSpec.swift
  lockbox-iosTests/ItemDetailPresenterSpec.swift
  lockbox-iosTests/PreferredBrowserSettingPresenterSpec.swift
  lockbox-iosTests/PreferredBrowserSettingViewSpec.swift
  lockbox-iosTests/RootPresenterSpec.swift
  lockbox-iosTests/SettingActionSpec.swift
  lockbox-iosTests/UserDefaults+Spec.swift
Labels: in progress

#247 deselect settings row after tapped
  Lockbox.xcodeproj/project.pbxproj
  lockbox-ios/View/SettingListView.swift
  lockbox-ios/View/TableViewCell/SettingCell.swift
  lockbox-iosTests/SettingListViewSpec.swift
Labels: bug, in progress

#257 Set the status bar color in SettingWebView screens
  lockbox-ios/View/SettingWebView.swift
  lockbox-iosTests/SettingWebViewSpec.swift
Labels: bug, in progress

#250 Expire the copy pasteboard after 60 seconds
  lockbox-ios/Action/CopyAction.swift
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-iosTests/CopyActionSpec.swift
Labels: in progress

#262 Change FxA blurb to attributed text and 1.5 line spacing
  lockbox-ios/Storyboard/Base.lproj/AccountSetting.storyboard
Labels: in progress

#263 Consolidate the view background colors to efeff4
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Storyboard/Base.lproj/SettingList.storyboard
  lockbox-ios/View/AutoLockSettingsView.swift
  lockbox-ios/View/ItemListView.swift
  lockbox-ios/View/PreferredBrowserSettingView.swift
  lockbox-ios/View/SettingListView.swift
Labels: in progress

#270 Replace show/hide password icon
  lockbox-ios/Common/Resources/Assets.xcassets/back-button.imageset/Contents.json
  lockbox-ios/Common/Resources/Assets.xcassets/back-button.imageset/backButton.png
  lockbox-ios/Common/Resources/Assets.xcassets/back-button.imageset/backButton@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/back-button.imageset/backButton@3x.png
  lockbox-ios/Common/Resources/Assets.xcassets/hide-eye.imageset/iconHide.png
  lockbox-ios/Common/Resources/Assets.xcassets/hide-eye.imageset/iconHide@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/hide-eye.imageset/iconHide@3x.png
  lockbox-ios/Common/Resources/Assets.xcassets/reveal-eye.imageset/iconReveal.png
  lockbox-ios/Common/Resources/Assets.xcassets/reveal-eye.imageset/iconReveal@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/reveal-eye.imageset/iconReveal@3x.png
  lockbox-ios/Storyboard/ItemDetail.storyboard
  lockbox-ios/View/ItemDetailView.swift
Labels: in progress

#271 Fix test data to include full origins and less items
  lockbox-ios/Action/DataStoreAction.swift
Labels: in progress

#259 Show a "Large" title in entry detail navigation
  lockbox-ios/Common/AppDelegate.swift
  lockbox-ios/Common/Extensions/UIImage+.swift
  lockbox-ios/View/FxAView.swift
  lockbox-ios/View/ItemDetailView.swift
  lockbox-ios/View/ItemListView.swift
  lockbox-ios/View/SettingListView.swift
  lockbox-ios/View/WelcomeView.swift
Labels: in progress

#269 Do not open browser window when preferred browser setting changes
  lockbox-ios/Action/ExternalLinkAction.swift
  lockbox-iosTests/ExternalLinkActionSpec.swift
Labels: in progress

#245 Biometrics for unlocking from visual lock
  Lockbox.xcodeproj/project.pbxproj
  lockbox-ios/Common/Extensions/LAContext+.swift
  lockbox-ios/Common/Extensions/UIImage+.swift
  lockbox-ios/Common/Helpers/BiometryManager.swift
  lockbox-ios/Common/Resources/Assets.xcassets/face.imageset/Contents.json
  lockbox-ios/Common/Resources/Assets.xcassets/fingerprint.imageset/Contents.json
  lockbox-ios/Presenter/RootPresenter.swift
  lockbox-ios/Presenter/SettingListPresenter.swift
  lockbox-ios/Presenter/WelcomePresenter.swift
  lockbox-ios/Storyboard/Base.lproj/Welcome.storyboard
  lockbox-ios/View/WelcomeView.swift
  lockbox-iosTests/BiometryManagerSpec.swift
  lockbox-iosTests/LAContext+Spec.swift
  lockbox-iosTests/RootPresenterSpec.swift
  lockbox-iosTests/RootViewSpec.swift
  lockbox-iosTests/SettingListPresenterSpec.swift
  lockbox-iosTests/UIColor+Spec.swift
  lockbox-iosTests/WelcomePresenterSpec.swift
  lockbox-iosTests/WelcomeViewSpec.swift
Labels: in progress

#276 Display preferred browser setting in list
  lockbox-ios/Action/ExternalLinkAction.swift
  lockbox-ios/Presenter/SettingListPresenter.swift
  lockbox-iosTests/SettingListPresenterSpec.swift
Labels: in progress

#261 Remove "Enable In Browser" help setting
  lockbox-ios/Action/RouteAction.swift
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Presenter/SettingListPresenter.swift
  lockbox-iosTests/RootViewSpec.swift
  lockbox-iosTests/SettingListViewSpec.swift
Labels: bug, in progress

#290 unpend rootviewspecs
  lockbox-ios/Presenter/RootPresenter.swift
  lockbox-ios/View/RootView.swift
  lockbox-iosTests/RootViewSpec.swift
Labels: in progress

#281 Display the settings button on iOS10 + small screens
  lockbox-ios/View/ItemListView.swift
Labels: in progress

#289 change highlight color for settings cells
  lockbox-ios/View/AutoLockSettingsView.swift
  lockbox-ios/View/PreferredBrowserSettingView.swift
Labels: in progress

#286 Alphabetically sort "open in browser" settings
  lockbox-ios/Presenter/PreferredBrowserSettingPresenter.swift
Labels: in progress

#288 Set color for web address in ItemDetailCell
  lockbox-ios/Presenter/ItemDetailPresenter.swift
  lockbox-ios/View/ItemDetailView.swift
  lockbox-iosTests/ItemDetailViewSpec.swift
Labels: in progress

#275 Send usage data setting
  lockbox-ios/Action/SettingAction.swift
  lockbox-ios/Common/Extensions/UserDefaults+.swift
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Presenter/SettingListPresenter.swift
  lockbox-ios/View/SettingListView.swift
  lockbox-ios/View/TableViewCell/SettingCell.swift
  lockbox-iosTests/SettingActionSpec.swift
  lockbox-iosTests/SettingListPresenterSpec.swift
  lockbox-iosTests/SettingListViewSpec.swift
  lockbox-iosTests/UIViewController+Spec.swift
  lockbox-iosTests/UserDefaults+Spec.swift
Labels: in progress

#297 Initial release notes and release preparation instructions
  docs/export-compliance.md
  docs/release-notes.md
  docs/releases.md
  mkdocs.yml
Labels: in progress

#294 Add confirmation dialog on unlink button
  lockbox-ios/Common/Extensions/UIViewController+.swift
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Presenter/AccountSettingPresenter.swift
  lockbox-ios/Presenter/ItemListPresenter.swift
  lockbox-ios/View/AccountSettingView.swift
  lockbox-iosTests/AccountSettingPresenterSpec.swift
  lockbox-iosTests/AccountSettingViewSpec.swift
  lockbox-iosTests/ItemListPresenterSpec.swift
  lockbox-iosTests/UIViewController+Spec.swift
Labels: in progress

#309 fix height on telemetry settings cell on iOS10
  lockbox-ios/View/TableViewCell/SettingCell.swift
Labels: in progress

#310 Fix opening links in chrome
  lockbox-ios/Action/ExternalLinkAction.swift
  lockbox-iosTests/ExternalLinkActionSpec.swift
Labels: in progress

#295 Import lockbox-ios-fxa-sync via carthage
  Cartfile
  Cartfile.resolved
  Lockbox.xcodeproj/project.pbxproj
  lockbox-ios/Common/AppDelegate.swift
  lockbox-ios/Common/Resources/Info.plist
Labels: in progress
