Repository mozilla-lockwise/lockwise-ios, pull requests merged in 2018-08, with the labels that each got.

#603 Remove buddybuild prebuild
  Lockbox.xcodeproj/project.pbxproj
  buddybuild_prebuild.sh
Labels: chore, in progress

#599 Store Account JSON after oauthInfo refresh
  lockbox-ios/Store/AccountStore.swift
Labels: in progress

#600 add note about how to contribute in contributing.md
  docs/contributing.md
Labels: in progress

#530 525-new-xcuitests
  LockboxXCUITests/LockBoxScreenGraph.swift
  LockboxXCUITests/LockboxXCUITests.swift
  lockbox-ios/Presenter/ItemDetailPresenter.swift
  lockbox-ios/Presenter/SettingListPresenter.swift
  lockbox-ios/Storyboard/Base.lproj/ItemList.storyboard
  lockbox-ios/View/AccountSettingView.swift
  lockbox-ios/View/ItemDetailView.swift
  lockbox-ios/View/ItemListView.swift
  lockbox-ios/View/PreferredBrowserSettingView.swift
  lockbox-ios/View/SettingListView.swift
  lockbox-iosTests/ItemDetailViewSpec.swift
  lockbox-iosTests/SettingListViewSpec.swift
Labels: in progress

#606 fix failing unitspecs
  Lockbox.xcodeproj/project.pbxproj
  lockbox-iosTests/AccountStoreSpec.swift
Labels: in progress

#586 autolock when appropriate on app foreground
  lockbox-ios/Store/AutoLockStore.swift
  lockbox-iosTests/AutoLockStoreSpec.swift
Labels: in progress

#607 More warnings cleanup
  lockbox-ios/View/OnboardingConfirmationView.swift
  lockbox-iosTests/OnboardingConfirmationViewSpec.swift
  lockbox-iosTests/RootPresenterSpec.swift
Labels: in progress

#619 store app version in keychain
  lockbox-ios/Common/AppDelegate.swift
  lockbox-ios/Store/AccountStore.swift
Labels: in progress

#618 update xcode version
  docs/install.md
Labels: in progress

#621 remove userdefaults.standard unless used in a non-subscription way
  Lockbox.xcodeproj/project.pbxproj
  lockbox-ios/Action/ExternalLinkAction.swift
  lockbox-ios/Action/SettingAction.swift
  lockbox-ios/Common/AppDelegate.swift
  lockbox-ios/Common/Extensions/UserDefaults+.swift
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Presenter/AutoLockSettingsPresenter.swift
  lockbox-ios/Presenter/ItemListPresenter.swift
  lockbox-ios/Presenter/PreferredBrowserSettingPresenter.swift
  lockbox-ios/Presenter/RootPresenter.swift
  lockbox-ios/Presenter/SettingListPresenter.swift
  lockbox-ios/Store/AutoLockStore.swift
  lockbox-ios/Store/DataStore.swift
  lockbox-ios/Store/UserDefaultStore.swift
  lockbox-ios/View/AutoLockSettingsView.swift
  lockbox-ios/View/PreferredBrowserSettingView.swift
  lockbox-iosTests/AutoLockSettingsPresenterSpec.swift
  lockbox-iosTests/AutoLockSettingsViewSpec.swift
  lockbox-iosTests/AutoLockStoreSpec.swift
  lockbox-iosTests/ExternalLinkActionSpec.swift
  lockbox-iosTests/ItemListPresenterSpec.swift
  lockbox-iosTests/PreferredBrowserSettingPresenterSpec.swift
  lockbox-iosTests/PreferredBrowserSettingViewSpec.swift
  lockbox-iosTests/RootPresenterSpec.swift
  lockbox-iosTests/SettingActionSpec.swift
  lockbox-iosTests/SettingListPresenterSpec.swift
  lockbox-iosTests/UserDefaultStoreSpec.swift
  lockbox-iosTests/UserDefaults+Spec.swift
Labels: in progress

#593 Removed `ActionHandler`s
  Cartfile.resolved
  Lockbox.xcodeproj/project.pbxproj
  Lockbox.xcodeproj/xcshareddata/xcschemes/lockbox.xcscheme
  lockbox-ios/Action/AccountAction.swift
  lockbox-ios/Action/ApplicationLifecycleAction.swift
  lockbox-ios/Action/CopyAction.swift
  lockbox-ios/Action/DataStoreAction.swift
  lockbox-ios/Action/ExternalLinkAction.swift
  lockbox-ios/Action/ItemDetailAction.swift
  lockbox-ios/Action/ItemListDisplayAction.swift
  lockbox-ios/Action/RouteAction.swift
  lockbox-ios/Common/AppDelegate.swift
  lockbox-ios/Presenter/AccountSettingPresenter.swift
  lockbox-ios/Presenter/AutoLockSettingsPresenter.swift
  lockbox-ios/Presenter/FxAPresenter.swift
  lockbox-ios/Presenter/ItemDetailPresenter.swift
  lockbox-ios/Presenter/ItemListPresenter.swift
  lockbox-ios/Presenter/OnboardingConfirmationPresenter.swift
  lockbox-ios/Presenter/PreferredBrowserSettingPresenter.swift
  lockbox-ios/Presenter/RootPresenter.swift
  lockbox-ios/Presenter/SettingListPresenter.swift
  lockbox-ios/Presenter/StaticURLPresenter.swift
  lockbox-ios/Presenter/WelcomePresenter.swift
  lockbox-ios/Store/AutoLockStore.swift
  lockbox-ios/Store/CopyConfirmationDisplayStore.swift
  lockbox-ios/Store/CopyDisplayStore.swift
  lockbox-ios/Store/ExternalLinkStore.swift
  lockbox-iosTests/AccountActionSpec.swift
  lockbox-iosTests/AccountSettingPresenterSpec.swift
  lockbox-iosTests/ApplicationLifecycleActionSpec.swift
  lockbox-iosTests/AutoLockSettingsPresenterSpec.swift
  lockbox-iosTests/AutoLockStoreSpec.swift
  lockbox-iosTests/CopyActionSpec.swift
  lockbox-iosTests/CopyConfirmationDisplayStoreSpec.swift
  lockbox-iosTests/CopyDisplayStoreSpec.swift
  lockbox-iosTests/DataStoreActionSpec.swift
  lockbox-iosTests/ExternalLinkActionSpec.swift
  lockbox-iosTests/ExternalLinkStoreSpec.swift
  lockbox-iosTests/FxAPresenterSpec.swift
  lockbox-iosTests/ItemDetailActionSpec.swift
  lockbox-iosTests/ItemDetailPresenterSpec.swift
  lockbox-iosTests/ItemListDisplayActionSpec.swift
  lockbox-iosTests/ItemListPresenterSpec.swift
  lockbox-iosTests/OnboardingConfirmationPresenterSpec.swift
  lockbox-iosTests/PreferredBrowserSettingPresenterSpec.swift
  lockbox-iosTests/RootPresenterSpec.swift
  lockbox-iosTests/RouteActionSpec.swift
  lockbox-iosTests/SettingActionSpec.swift
  lockbox-iosTests/SettingListPresenterSpec.swift
  lockbox-iosTests/WelcomePresenterSpec.swift
Labels: in progress

#625 fix failing needs email confirmation state
  LockboxXCUITests/LockboxXCUITests.swift
Labels: in progress

#620 Adjust integration
  Cartfile
  Cartfile.resolved
  Lockbox.xcodeproj/project.pbxproj
  lockbox-ios/Common/AppDelegate.swift
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Presenter/RootPresenter.swift
Labels: in progress

#628 Ignore dynamic type settings for navigation bar items
  Lockbox.xcodeproj/project.pbxproj
  lockbox-ios/Common/Extensions/UIFont+.swift
  lockbox-ios/View/AccountSettingView.swift
  lockbox-ios/View/AutoLockSettingsView.swift
  lockbox-ios/View/FxAView.swift
  lockbox-ios/View/ItemDetailView.swift
  lockbox-ios/View/ItemListView.swift
  lockbox-ios/View/PreferredBrowserSettingView.swift
  lockbox-ios/View/SettingListView.swift
  lockbox-ios/View/StaticURLWebView.swift
Labels: in progress

#598 OAuth upgrade path dialog and handling
  Lockbox.xcodeproj/project.pbxproj
  lockbox-ios/Action/AccountAction.swift
  lockbox-ios/Action/ApplicationLifecycleAction.swift
  lockbox-ios/Common/AppDelegate.swift
  lockbox-ios/Common/Extensions/FxAClient+.swift
  lockbox-ios/Common/Extensions/UIViewController+.swift
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Common/Resources/Info.plist
  lockbox-ios/Presenter/ItemListPresenter.swift
  lockbox-ios/Presenter/RootPresenter.swift
  lockbox-ios/Presenter/WelcomePresenter.swift
  lockbox-ios/Store/AccountStore.swift
  lockbox-ios/Store/DataStore.swift
  lockbox-ios/Storyboard/LaunchScreen.storyboard
  lockbox-ios/View/RootView.swift
  lockbox-iosTests/AccountActionSpec.swift
  lockbox-iosTests/AccountStoreSpec.swift
  lockbox-iosTests/AutoLockStoreSpec.swift
  lockbox-iosTests/CopyDisplayStoreSpec.swift
  lockbox-iosTests/ItemDetailPresenterSpec.swift
  lockbox-iosTests/ItemListPresenterSpec.swift
  lockbox-iosTests/RootPresenterSpec.swift
  lockbox-iosTests/RootViewSpec.swift
  lockbox-iosTests/UIViewController+Spec.swift
  lockbox-iosTests/WelcomePresenterSpec.swift
Labels: in progress

#629 Add release notes for 1.2 version
  docs/release-notes.md
Labels: chore, in progress

#632 fix cancel button on long search term
  lockbox-ios/Storyboard/Base.lproj/ItemList.storyboard
Labels: in progress

#633 make sure to preserve current version even when clearing keychain
  lockbox-ios/Common/AppDelegate.swift
  lockbox-ios/Store/AccountStore.swift
  lockbox-ios/Store/UserDefaultStore.swift
Labels: in progress

#636 Add base Sentry integration
  Cartfile
  Cartfile.resolved
  Lockbox.xcodeproj/project.pbxproj
  buddybuild_prebuild.sh
  lockbox-ios/Common/Helpers/SentryManager.swift
  lockbox-ios/Common/Resources/Info.plist
  lockbox-ios/Presenter/RootPresenter.swift
  lockbox-iosTests/RootPresenterSpec.swift
Labels: in progress

#642 Split the schemes up and clean up simulator
  Lockbox.xcodeproj/xcshareddata/xcschemes/lockbox.xcscheme
  Lockbox.xcodeproj/xcshareddata/xcschemes/uispecs.xcscheme
  Lockbox.xcodeproj/xcshareddata/xcschemes/unitspecs.xcscheme
Labels: in progress

#644 Replace references to missing arrowhead
  lockbox-ios/Common/Resources/Assets.xcassets/arrow-right.imageset/back.png
  lockbox-ios/Common/Resources/Assets.xcassets/arrow-right.imageset/back@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/arrow-right.imageset/back@3x.png
  lockbox-ios/Storyboard/Base.lproj/ItemDetail.storyboard
  lockbox-ios/Storyboard/Base.lproj/ItemList.storyboard
Labels: in progress

#660 add login and disconnect oauth telemetry events
  lockbox-ios/Action/AccountAction.swift
  lockbox-ios/Action/TelemetryAction.swift
  lockbox-iosTests/TelemetryStoreSpec.swift
Labels: in progress, metrics

#652 Webview spinner
  lockbox-ios/View/StaticURLWebView.swift
  lockbox-iosTests/StaticURLWebViewSpec.swift
Labels: in progress

#671 Bump version to 1.3
  lockbox-ios/Common/Resources/Info.plist
Labels: in progress

#668 Add "Add a browser" documentation
  buddybuild_postbuild.sh
  docs/add-a-browser.md
  mkdocs.yml
Labels: in progress

#667 Update release instructions with latest and greatest
  docs/export-compliance.md
  docs/releases.md
Labels: in progress
