Repository mozilla-lockwise/lockwise-ios, pull requests merged in 2018-03, with the labels that each got.

#129 Added cjose error handling and garbage collection
  lockbox-ios/Action/FxAAction.swift
  lockbox-ios/Common/Helpers/KeyManager.swift
  lockbox-iosTests/FxAActionSpec.swift
  lockbox-iosTests/KeyManagerSpec.swift
Labels: no-pi

#154 Add metrics plan; Define event methods and objects
  docs/metrics.md
  lockbox-ios/Common/AppDelegate.swift
  lockbox-ios/TelemetryIntegration.swift
Labels: in progress

#147 Settings main screen
  Lockbox.xcodeproj/project.pbxproj
  lockbox-ios/Action/RouteAction.swift
  lockbox-ios/Action/UserInfoAction.swift
  lockbox-ios/Common/Helpers/KeychainManager.swift
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Presenter/ItemListPresenter.swift
  lockbox-ios/Presenter/RootPresenter.swift
  lockbox-ios/Presenter/SettingsPresenter.swift
  lockbox-ios/Store/UserInfoStore.swift
  lockbox-ios/View/ItemListView.swift
  lockbox-ios/View/NavigationController/MainNavigationController.swift
  lockbox-ios/View/RootView.swift
  lockbox-ios/View/SettingsView.swift
  lockbox-iosTests/MainNavigationControllerSpec.swift
  lockbox-iosTests/RootPresenterSpec.swift
  lockbox-iosTests/RootViewSpec.swift
  lockbox-iosTests/SettingsPresenterSpec.swift
  lockbox-iosTests/SettingsViewSpec.swift
Labels: in progress

#169 Load FxA sign in mode not default sign up mode
  lockbox-ios/Action/FxAAction.swift
  lockbox-iosTests/FxAActionSpec.swift
Labels: feature, in progress
