Repository mozilla-lockwise/lockwise-ios, pull requests merged in 2018-05, with the labels that each got.

#277 Enable biometrics in onboarding flow
  Lockbox.xcodeproj/project.pbxproj
  lockbox-ios/Action/RouteAction.swift
  lockbox-ios/Common/Extensions/UIDevice+.swift
  lockbox-ios/Common/Helpers/BiometryManager.swift
  lockbox-ios/Common/Resources/Assets.xcassets/face-large.imageset/Contents.json
  lockbox-ios/Common/Resources/Assets.xcassets/face-large.imageset/faceId.png
  lockbox-ios/Common/Resources/Assets.xcassets/face-large.imageset/faceId@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/face-large.imageset/faceId@3x.png
  lockbox-ios/Common/Resources/Assets.xcassets/fingerprint-large.imageset/Contents.json
  lockbox-ios/Common/Resources/Assets.xcassets/fingerprint-large.imageset/touchId.png
  lockbox-ios/Common/Resources/Assets.xcassets/fingerprint-large.imageset/touchId@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/fingerprint-large.imageset/touchId@3x.png
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Common/Resources/Info.plist
  lockbox-ios/Presenter/BiometryOnboardingPresenter.swift
  lockbox-ios/Presenter/FxAPresenter.swift
  lockbox-ios/Presenter/RootPresenter.swift
  lockbox-ios/Presenter/SettingListPresenter.swift
  lockbox-ios/Presenter/WelcomePresenter.swift
  lockbox-ios/Store/FxAStore.swift
  lockbox-ios/Storyboard/Base.lproj/BiometryOnboarding.storyboard
  lockbox-ios/Storyboard/de.lproj/BiometryOnboarding.strings
  lockbox-ios/Storyboard/en.lproj/BiometryOnboarding.strings
  lockbox-ios/Storyboard/es.lproj/BiometryOnboarding.strings
  lockbox-ios/View/BiometryOnboardingView.swift
  lockbox-ios/View/RootView.swift
  lockbox-iosTests/BiometryOnboardingPresenterSpec.swift
  lockbox-iosTests/BiometryOnboardingViewSpec.swift
  lockbox-iosTests/FxAPresenterSpec.swift
  lockbox-iosTests/FxAStoreSpec.swift
  lockbox-iosTests/RootViewSpec.swift
Labels: in progress

#319 Add cancel button for filter
  lockbox-ios/Presenter/ItemListPresenter.swift
  lockbox-ios/Storyboard/Base.lproj/ItemList.storyboard
  lockbox-ios/View/ItemListView.swift
  lockbox-ios/View/TableViewCell/FilterCell.swift
  lockbox-iosTests/ItemListPresenterSpec.swift
  lockbox-iosTests/ItemListViewSpec.swift
Labels: in progress

#320 Latest copy and content updates
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Presenter/AccountSettingPresenter.swift
  lockbox-ios/Storyboard/Base.lproj/AccountSetting.storyboard
  lockbox-ios/Storyboard/Base.lproj/EntryEditDisclaimer.xib
  lockbox-ios/Storyboard/StatusAlert.xib
  lockbox-ios/Storyboard/de.lproj/EntryEditDisclaimer.strings
  lockbox-ios/Storyboard/en.lproj/EntryEditDisclaimer.strings
  lockbox-ios/Storyboard/es.lproj/EntryEditDisclaimer.strings
  lockbox-ios/View/FxAView.swift
  lockbox-ios/View/SettingListView.swift
Labels: in progress

#322 Rename to Firefox Lockbox
  Lockbox.xcodeproj/project.pbxproj
  Lockbox.xcodeproj/xcshareddata/xcschemes/lockbox.xcscheme
  README.md
  docs/architecture.md
  docs/index.md
  docs/metrics.md
  docs/updating_libraries.md
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Common/Resources/Strings/de.lproj/Localizable.strings
  lockbox-ios/Common/Resources/Strings/en.lproj/Localizable.strings
  lockbox-ios/Common/Resources/Strings/es.lproj/Localizable.strings
  lockbox-ios/Storyboard/Base.lproj/AccountSetting.storyboard
  lockbox-ios/Storyboard/Base.lproj/EmptyList.xib
  lockbox-ios/Storyboard/de.lproj/EmptyList.strings
  lockbox-ios/Storyboard/en.lproj/EmptyList.strings
  lockbox-ios/Storyboard/es.lproj/EmptyList.strings
  lockbox-iosTests/FxAPresenterSpec.swift
  mkdocs.yml
Labels: in progress

#334 fix specs firefox_lockbox
  Lockbox.xcodeproj/project.pbxproj
Labels: in progress

#335 Set FxA redirect_uri back to expected
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-iosTests/FxAPresenterSpec.swift
Labels: bug, in progress

#326 Build the auto lock timer
  Lockbox.xcodeproj/project.pbxproj
  lockbox-ios/Action/SettingAction.swift
  lockbox-ios/Presenter/RootPresenter.swift
  lockbox-ios/Store/AutoLockStore.swift
  lockbox-iosTests/AutoLockStoreSpec.swift
  lockbox-iosTests/RootPresenterSpec.swift
Labels: in progress

#324 Update launch screen and welcome content
  lockbox-ios/Common/Resources/Assets.xcassets/arrowhead-right-16.imageset/Contents.json
  lockbox-ios/Common/Resources/Assets.xcassets/arrowhead-right-16.imageset/arrowheadRight16.png
  lockbox-ios/Common/Resources/Assets.xcassets/arrowhead-right-16.imageset/arrowheadRight16@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/arrowhead-right-16.imageset/arrowheadRight16@3x.png
  lockbox-ios/Common/Resources/Assets.xcassets/lockbox-title.imageset/lockbox.png
  lockbox-ios/Common/Resources/Assets.xcassets/lockbox-title.imageset/lockbox@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/lockbox-title.imageset/lockbox@3x.png
  lockbox-ios/Presenter/WelcomePresenter.swift
  lockbox-ios/Storyboard/Base.lproj/Welcome.storyboard
  lockbox-ios/Storyboard/LaunchScreen.storyboard
  lockbox-ios/Storyboard/de.lproj/Welcome.strings
  lockbox-ios/Storyboard/en.lproj/Welcome.strings
  lockbox-ios/Storyboard/es.lproj/Welcome.strings
  lockbox-ios/View/WelcomeView.swift
  lockbox-iosTests/WelcomePresenterSpec.swift
  lockbox-iosTests/WelcomeViewSpec.swift
Labels: in progress

#341 Add PI test plan
  docs/test-plan.md
Labels: in progress

#345 provide placeholder string when profileinfo not populated
  lockbox-ios/Common/AppDelegate.swift
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Presenter/RootPresenter.swift
  lockbox-ios/Presenter/WelcomePresenter.swift
  lockbox-ios/Store/DataStore.swift
  lockbox-ios/Storyboard/Base.lproj/AccountSetting.storyboard
  lockbox-iosTests/WelcomePresenterSpec.swift
Labels: in progress

#353 Update "Clear out Firefox Lockbox" titles and descriptions
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Storyboard/Base.lproj/AccountSetting.storyboard
Labels: in progress

#336 Put lock now button in the table view footer
  lockbox-ios/Storyboard/Base.lproj/SettingList.storyboard
Labels: in progress

#349 Update the client id in lockbox-ios-fxa-sync library
  Cartfile
  Cartfile.resolved
Labels: in progress

#311 Update metrics.md; add telemetry events
  docs/metrics.md
  lockbox-ios/Action/ItemDetailAction.swift
  lockbox-ios/Action/RouteAction.swift
  lockbox-ios/Action/SettingAction.swift
  lockbox-ios/Action/TelemetryAction.swift
  lockbox-iosTests/ItemDetailActionSpec.swift
  lockbox-iosTests/RouteActionSpec.swift
  lockbox-iosTests/SettingActionSpec.swift
  lockbox-iosTests/TelemetryActionSpec.swift
  lockbox-iosTests/TelemetryStoreSpec.swift
Labels: in progress

#344 Update biometrics strings
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Common/Resources/Info.plist
Labels: in progress

#363 listen for every foreground action
  lockbox-ios/Presenter/WelcomePresenter.swift
  lockbox-iosTests/WelcomePresenterSpec.swift
Labels: in progress

#355 Fix spacing on cancel button
  lockbox-ios/Storyboard/Base.lproj/ItemList.storyboard
  lockbox-ios/View/ItemListView.swift
Labels: in progress

#357 Add test/release notes for latest TestFlight build
  docs/release-notes.md
Labels: in progress

#346 loading indication for syncing
  Lockbox.xcodeproj/project.pbxproj
  lockbox-ios/Common/Extensions/UIViewController+.swift
  lockbox-ios/Common/Resources/Assets.xcassets/item-list-placeholder.imageset/Contents.json
  lockbox-ios/Common/Resources/Assets.xcassets/item-list-placeholder.imageset/placeholderEntries.png
  lockbox-ios/Common/Resources/Assets.xcassets/item-list-placeholder.imageset/placeholderEntries@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/item-list-placeholder.imageset/placeholderEntries@3x.png
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Presenter/ItemListPresenter.swift
  lockbox-ios/Store/DataStore.swift
  lockbox-ios/Storyboard/Base.lproj/EmptyList.xib
  lockbox-ios/Storyboard/Base.lproj/ItemList.storyboard
  lockbox-ios/Storyboard/Base.lproj/SpinnerAlert.xib
  lockbox-ios/Storyboard/de.lproj/EmptyList.strings
  lockbox-ios/Storyboard/de.lproj/SpinnerAlert.strings
  lockbox-ios/Storyboard/en.lproj/EmptyList.strings
  lockbox-ios/Storyboard/en.lproj/SpinnerAlert.strings
  lockbox-ios/Storyboard/es.lproj/EmptyList.strings
  lockbox-ios/Storyboard/es.lproj/SpinnerAlert.strings
  lockbox-ios/View/ItemListView.swift
  lockbox-ios/View/SpinnerAlert.swift
  lockbox-iosTests/ItemListPresenterSpec.swift
  lockbox-iosTests/ItemListViewSpec.swift
  lockbox-iosTests/UIViewController+Spec.swift
Labels: in progress

#356 Fix auto-lock timer
  lockbox-ios/Store/AutoLockStore.swift
Labels: MVP, P1, bug, in progress

#368 fixes filtering / cancelling
  lockbox-ios/Action/ItemListDisplayAction.swift
  lockbox-ios/Presenter/ItemListPresenter.swift
  lockbox-ios/Storyboard/Base.lproj/ItemList.storyboard
  lockbox-ios/View/ItemListView.swift
  lockbox-iosTests/ItemListPresenterSpec.swift
  lockbox-iosTests/ItemListViewSpec.swift
Labels: in progress

#358 Hook up "Learn more" link on Welcome first run screen
  Lockbox.xcodeproj/project.pbxproj
  lockbox-ios/Action/RouteAction.swift
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Presenter/RootPresenter.swift
  lockbox-ios/Presenter/WelcomePresenter.swift
  lockbox-ios/View/RootView.swift
  lockbox-ios/View/StaticURLWebView.swift
  lockbox-ios/View/WelcomeView.swift
  lockbox-iosTests/RootViewSpec.swift
  lockbox-iosTests/StaticURLWebViewSpec.swift
  lockbox-iosTests/WelcomePresenterSpec.swift
Labels: in progress

#397 Improved item list placeholder and sync spinner
  lockbox-ios/Common/Resources/Assets.xcassets/item-list-placeholder.imageset/Contents.json
  lockbox-ios/Common/Resources/Assets.xcassets/item-list-placeholder.imageset/placeholderEntries.png
  lockbox-ios/Common/Resources/Assets.xcassets/item-list-placeholder.imageset/placeholderEntries@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/item-list-placeholder.imageset/placeholderEntries@3x.png
  lockbox-ios/Common/Resources/Assets.xcassets/item-list-placeholder.imageset/syncing-placeholder-img.png
  lockbox-ios/Common/Resources/Assets.xcassets/item-list-placeholder.imageset/syncing-placeholder-img@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/item-list-placeholder.imageset/syncing-placeholder-img@3x.png
  lockbox-ios/Storyboard/Base.lproj/ItemList.storyboard
  lockbox-ios/Storyboard/Base.lproj/SpinnerAlert.xib
Labels: in progress

#389 reset auto lock timer when setting changes
  lockbox-ios/Store/AutoLockStore.swift
  lockbox-iosTests/AutoLockStoreSpec.swift
Labels: in progress

#385 tweak list display logic so that list displays when launching in unlocked state
  lockbox-ios/Presenter/RootPresenter.swift
  lockbox-ios/Presenter/WelcomePresenter.swift
  lockbox-iosTests/RootPresenterSpec.swift
  lockbox-iosTests/WelcomePresenterSpec.swift
Labels: in progress

#387 updated release notes for another pre-release
  docs/release-notes.md
Labels: in progress

#403 Settings button cut off in Account page (#337)
  lockbox-ios/View/AccountSettingView.swift
Labels: in progress

#390 Change global background container color (#367)
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Storyboard/Base.lproj/AccountSetting.storyboard
  lockbox-ios/Storyboard/Base.lproj/ItemList.storyboard
  lockbox-ios/Storyboard/Base.lproj/SettingList.storyboard
  lockbox-ios/Storyboard/ItemDetail.storyboard
  lockbox-ios/View/AccountSettingView.swift
  lockbox-ios/View/ItemDetailView.swift
  lockbox-ios/View/ItemListView.swift
  lockbox-ios/View/SettingListView.swift
Labels: in progress

#406 Fix some buildtime warnings
  Lockbox.xcodeproj/project.pbxproj
  lockbox-ios/Presenter/ItemListPresenter.swift
  lockbox-ios/Presenter/WelcomePresenter.swift
  lockbox-ios/Store/DataStore.swift
  lockbox-ios/Storyboard/Base.lproj/SettingList.storyboard
  lockbox-ios/Storyboard/ItemDetail.storyboard
  lockbox-ios/View/FxAView.swift
  lockbox-ios/View/ItemListView.swift
Labels: P2, chore, in progress

#399 make sure all characters in password are represented by •
  lockbox-ios/Presenter/ItemDetailPresenter.swift
  lockbox-iosTests/ItemDetailPresenterSpec.swift
Labels: in progress

#411 Update docs with additional release instructions
  docs/releases.md
Labels: chore, in progress

#407 warn users before attempting to use app without passcode
  lockbox-ios/Action/ExternalLinkAction.swift
  lockbox-ios/Common/Helpers/BiometryManager.swift
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Presenter/ItemDetailPresenter.swift
  lockbox-ios/Presenter/WelcomePresenter.swift
  lockbox-iosTests/BiometryManagerSpec.swift
  lockbox-iosTests/ExternalLinkActionSpec.swift
  lockbox-iosTests/ItemDetailPresenterSpec.swift
  lockbox-iosTests/WelcomePresenterSpec.swift
Labels: in progress

#412 Introduce state machine to model storage state and sync state.
  Cartfile.resolved
  lockbox-ios/Store/DataStore.swift
Labels: in progress

#418 restart timer whenever user interacts with application
  lockbox-ios/Store/AutoLockStore.swift
  lockbox-iosTests/AutoLockStoreSpec.swift
Labels: in progress

#413 Update navigation bar action links
  Lockbox.xcodeproj/project.pbxproj
  lockbox-ios/Common/Extensions/UIButton+.swift
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Presenter/AutoLockSettingsPresenter.swift
  lockbox-ios/Presenter/FxAPresenter.swift
  lockbox-ios/Presenter/PreferredBrowserSettingPresenter.swift
  lockbox-ios/View/AccountSettingView.swift
  lockbox-ios/View/AutoLockSettingsView.swift
  lockbox-ios/View/FxAView.swift
  lockbox-ios/View/ItemDetailView.swift
  lockbox-ios/View/ItemListView.swift
  lockbox-ios/View/PreferredBrowserSettingView.swift
  lockbox-iosTests/FxAPresenterSpec.swift
  lockbox-iosTests/UIButton+Spec.swift
Labels: in progress

#423 Release notes for Wednesday pre-release
  docs/release-notes.md
Labels: in progress

#429 Remove unused German and Spanish localizations and files
  Lockbox.xcodeproj/project.pbxproj
  lockbox-ios/Common/Resources/Strings/de.lproj/Localizable.strings
  lockbox-ios/Common/Resources/Strings/es.lproj/Localizable.strings
  lockbox-ios/Storyboard/de.lproj/AccountSetting.strings
  lockbox-ios/Storyboard/de.lproj/EntryEditDisclaimer.strings
  lockbox-ios/Storyboard/de.lproj/ItemList.strings
  lockbox-ios/Storyboard/de.lproj/SettingList.strings
  lockbox-ios/Storyboard/de.lproj/SpinnerAlert.strings
  lockbox-ios/Storyboard/de.lproj/Welcome.strings
  lockbox-ios/Storyboard/es.lproj/AccountSetting.strings
  lockbox-ios/Storyboard/es.lproj/EntryEditDisclaimer.strings
  lockbox-ios/Storyboard/es.lproj/ItemList.strings
  lockbox-ios/Storyboard/es.lproj/SettingList.strings
  lockbox-ios/Storyboard/es.lproj/SpinnerAlert.strings
  lockbox-ios/Storyboard/es.lproj/Welcome.strings
Labels: in progress

#400 check that script messages come from original url
  lockbox-ios/View/FxAView.swift
Labels: in progress

#435 Expand www title to include optional digits afterwards
  lockbox-ios/Common/Extensions/String+.swift
  lockbox-iosTests/String+Spec.swift
Labels: in progress

#436 Login route events
  docs/metrics.md
  lockbox-ios/Action/RouteAction.swift
  lockbox-ios/Action/TelemetryAction.swift
  lockbox-iosTests/RouteActionSpec.swift
  lockbox-iosTests/TelemetryStoreSpec.swift
Labels: in progress

#419 unlock automatically when device auth has become unavailable
  lockbox-ios/Presenter/RootPresenter.swift
  lockbox-ios/Presenter/SettingListPresenter.swift
  lockbox-ios/Presenter/WelcomePresenter.swift
  lockbox-ios/View/SettingListView.swift
  lockbox-iosTests/RootPresenterSpec.swift
  lockbox-iosTests/SettingListPresenterSpec.swift
  lockbox-iosTests/SettingListViewSpec.swift
  lockbox-iosTests/WelcomePresenterSpec.swift
Labels: in progress

#438 Add UI for new preparing state
  lockbox-ios/Common/Resources/Assets.xcassets/preparing-placeholder.imageset/Contents.json
  lockbox-ios/Common/Resources/Assets.xcassets/preparing-placeholder.imageset/mail.png
  lockbox-ios/Common/Resources/Assets.xcassets/preparing-placeholder.imageset/mail@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/preparing-placeholder.imageset/mail@3x.png
  lockbox-ios/Presenter/FxAPresenter.swift
  lockbox-ios/Presenter/ItemListPresenter.swift
  lockbox-ios/Presenter/RootPresenter.swift
  lockbox-ios/Store/DataStore.swift
  lockbox-ios/Storyboard/Base.lproj/ItemList.storyboard
  lockbox-ios/View/ItemListView.swift
  lockbox-iosTests/ItemListPresenterSpec.swift
  lockbox-iosTests/ItemListViewSpec.swift
  lockbox-iosTests/RootPresenterSpec.swift
Labels: in progress

#402 pull to refresh
  lockbox-ios/Action/ItemListDisplayAction.swift
  lockbox-ios/Presenter/ItemListPresenter.swift
  lockbox-ios/View/ItemListView.swift
  lockbox-iosTests/ItemListPresenterSpec.swift
Labels: in progress

#452 make sure to unlock when there _is_ a profile but no locked value set
  lockbox-ios/Store/DataStore.swift
Labels: in progress

#430 add learn more button hookup
  Lockbox.xcodeproj/project.pbxproj
  lockbox-ios/Action/RouteAction.swift
  lockbox-ios/Action/TelemetryAction.swift
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Presenter/ItemDetailPresenter.swift
  lockbox-ios/Presenter/ItemListPresenter.swift
  lockbox-ios/Presenter/RootPresenter.swift
  lockbox-ios/Presenter/SettingListPresenter.swift
  lockbox-ios/Presenter/StaticURLPresenter.swift
  lockbox-ios/Presenter/WelcomePresenter.swift
  lockbox-ios/Storyboard/Base.lproj/EntryEditDisclaimer.xib
  lockbox-ios/Storyboard/Base.lproj/ItemDetail.storyboard
  lockbox-ios/Storyboard/en.lproj/EntryEditDisclaimer.strings
  lockbox-ios/Storyboard/en.lproj/ItemDetail.strings
  lockbox-ios/View/ItemDetailView.swift
  lockbox-ios/View/NavigationController/ExternalWebsiteNavigationController.swift
  lockbox-ios/View/RootView.swift
  lockbox-ios/View/SettingListView.swift
  lockbox-ios/View/StaticURLWebView.swift
  lockbox-iosTests/AutoLockStoreSpec.swift
  lockbox-iosTests/ItemDetailPresenterSpec.swift
  lockbox-iosTests/ItemDetailViewSpec.swift
  lockbox-iosTests/ItemListPresenterSpec.swift
  lockbox-iosTests/RootPresenterSpec.swift
  lockbox-iosTests/RootViewSpec.swift
  lockbox-iosTests/RouteActionSpec.swift
  lockbox-iosTests/SettingListPresenterSpec.swift
  lockbox-iosTests/SettingListViewSpec.swift
  lockbox-iosTests/StaticURLWebViewSpec.swift
  lockbox-iosTests/WelcomePresenterSpec.swift
Labels: in progress

#442 Document accesibility testing plan
  docs/test-plan.md
Labels: in progress

#457 Remove onAppExit autolock setting for initial release
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Presenter/AutoLockSettingsPresenter.swift
  lockbox-ios/Presenter/RootPresenter.swift
  lockbox-ios/Store/AutoLockStore.swift
  lockbox-ios/Store/UserInfoStore.swift
  lockbox-iosTests/AutoLockSettingsPresenterSpec.swift
  lockbox-iosTests/AutoLockStoreSpec.swift
  lockbox-iosTests/ItemListPresenterSpec.swift
  lockbox-iosTests/RootPresenterSpec.swift
  lockbox-iosTests/UserDefaults+Spec.swift
Labels: in progress

#455 add accessibility configuration
  lockbox-ios/Common/Extensions/UIViewController+.swift
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Presenter/ItemDetailPresenter.swift
  lockbox-ios/Presenter/ItemListPresenter.swift
  lockbox-ios/Presenter/SettingListPresenter.swift
  lockbox-ios/Storyboard/Base.lproj/ItemDetail.storyboard
  lockbox-ios/Storyboard/Base.lproj/Welcome.storyboard
  lockbox-ios/View/FxAView.swift
  lockbox-ios/View/ItemDetailView.swift
  lockbox-ios/View/ItemListView.swift
  lockbox-ios/View/PreferredBrowserSettingView.swift
  lockbox-ios/View/SettingListView.swift
  lockbox-iosTests/ItemDetailPresenterSpec.swift
  lockbox-iosTests/ItemDetailViewSpec.swift
Labels: in progress

#458 re-add biometric unlock button
  lockbox-ios/Common/Helpers/BiometryManager.swift
  lockbox-ios/Common/Resources/Assets.xcassets/unlock.imageset/Contents.json
  lockbox-ios/Common/Resources/Assets.xcassets/unlock.imageset/icon-unlock.png
  lockbox-ios/Common/Resources/Assets.xcassets/unlock.imageset/icon-unlock@2x.png
  lockbox-ios/Common/Resources/Assets.xcassets/unlock.imageset/icon-unlock@3x.png
  lockbox-ios/Common/Resources/Constants.swift
  lockbox-ios/Presenter/WelcomePresenter.swift
  lockbox-ios/Storyboard/Base.lproj/Welcome.storyboard
  lockbox-ios/View/WelcomeView.swift
  lockbox-iosTests/BiometryManagerSpec.swift
  lockbox-iosTests/WelcomePresenterSpec.swift
  lockbox-iosTests/WelcomeViewSpec.swift
Labels: in progress
